name: IGVC Compile Test

on:
  pull_request:
    branches:
    - master
    types:
    - opened
    - synchronize
  pull_request_review:
    types: [submitted]

jobs:
  test:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED' && github.base_ref == 'master' && 
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile

  fail_otherwise:
    if: github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Try to fail
        run: exit 1
