name: IGVC Compile Test

on:
  pull_request_review:
    types: [submitted]

jobs:
  test_after_approval:
    if: github.event.review.state == 'approved'
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile
